"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.aiService = void 0;
const ollama_service_1 = require("@/services/ollama.service");
const prompts_1 = require("@/utils/prompts");
const types_1 = require("@/types");
const logger_1 = require("@/utils/logger");
const ApiError_1 = require("@/utils/ApiError");
const DEMO_MODE = process.env.DEMO_MODE === "true";
const MOCK_REVIEW_RESPONSE = {
    summary: "This is a demo response. In the full offline version, this analysis is generated by a local LLM running via Ollama, ensuring zero data leaves your machine.",
    correctedCode: "",
    overallScore: 85,
    issues: [
        {
            line: 12,
            severity: types_1.SeverityLevel.INFO,
            title: "Demo: Potential null reference",
            description: "This is a sample issue shown in demo mode. Deploy locally with Ollama for real AI analysis.",
            suggestion: "Deploy locally with Ollama for real AI analysis.",
        },
    ],
};
class AiService {
    async reviewCode(code, language) {
        if (DEMO_MODE) {
            logger_1.logger.info("Running in DEMO_MODE - returning mock AI response");
            await new Promise((resolve) => setTimeout(resolve, 1500));
            return MOCK_REVIEW_RESPONSE;
        }
        const prompt = (0, prompts_1.buildCodeReviewPrompt)(code, language);
        logger_1.logger.info(`Sending code to AI model for review (language: ${language})`);
        const rawResponse = await ollama_service_1.ollamaService.generate(prompt);
        return this.parseAiResponse(rawResponse);
    }
    parseAiResponse(rawResponse) {
        try {
            const cleaned = rawResponse
                .replace(/```json/g, "")
                .replace(/```/g, "")
                .trim();
            const jsonMatch = cleaned.match(/\{[\s\S]*\}/);
            if (!jsonMatch) {
                throw new Error("No JSON object found in AI response");
            }
            const parsed = JSON.parse(jsonMatch[0]);
            const result = {
                summary: parsed.summary || "No summary provided.",
                correctedCode: typeof parsed.correctedCode === "string"
                    ? parsed.correctedCode
                    : "",
                overallScore: typeof parsed.overallScore === "number"
                    ? parsed.overallScore
                    : 50,
                issues: Array.isArray(parsed.issues)
                    ? parsed.issues.map((issue) => ({
                        line: typeof issue.line === "number"
                            ? issue.line
                            : 1,
                        severity: this.normalizeSeverity(issue.severity),
                        title: issue.title || "Untitled Issue",
                        description: issue.description || "",
                        suggestion: issue.suggestion || "",
                    }))
                    : [],
            };
            return result;
        }
        catch (error) {
            logger_1.logger.error(`Failed to parse AI response: ${error.message}`);
            logger_1.logger.error(`Raw response was: ${rawResponse.slice(0, 500)}`);
            throw new ApiError_1.ApiError(502, "AI returned an unexpected response format. Please try again.");
        }
    }
    normalizeSeverity(value) {
        const valid = Object.values(types_1.SeverityLevel);
        return valid.includes(value)
            ? value
            : types_1.SeverityLevel.INFO;
    }
}
exports.aiService = new AiService();
//# sourceMappingURL=ai.service.js.map